### ISSUE TITLE
Is this being maintained?

### ISSUE THREAD

**Issue by theklr** [TomFreudenberg/next-auth-mock#10]
Just wanted to know if there are plans with updating and maintaining  this package. Noticing issues without comments  since Jan this year.

**Comment by TomFreudenberg** [comment]
Hi @theklr Kevin

It's been a while since using this component, while not so happy with nextauth anymore.
In general I try to keep my repos in live, so what is your case for coming up?

Thanks
Tom

**Comment by theklr** [comment]
Was just verifying if it was active in terms of support dependency. Wanted to know if I should fork or wait for an update  if I was going to add to my work's package system.

**Comment by TomFreudenberg** [comment]
So, stay in contact :-)
